theme: minima
title: Manuel Ferrer-Garcia
description: 
  Welcome to my personal website.
  
# Add links to navigation
navbar:
  - name: Home
    link: /
  - name: Publications
    link: /publications.html
